### ISSUE TITLE
Add flake8 to tests

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/carbon#40]
pipenv removed flake8 support so this will need to be run by explicitly calling flake8

**Comment by JPrevost** [comment]
You may want to consider CodeClimate to lint the PR diff. I think they technically use PEP8 via `pycodestyle` and not flake8 but I suspect that's just a different implementation.

**Comment by gravesm** [comment]
I'll probably just add another tox env for flake8 so it can be run locally before submitting, and then add it to the travis matrix for ci. It's probably like a two line fix.
